[project]
name = "chronotui"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "platformdirs>=4.3.8",
    "textual>=3.7.1",
]
